### ISSUE TITLE
Add steps to deploy a web frontend on the cluster itself

### ISSUE THREAD

**Issue by mulbc** [pcuzner/fioloadgen#2]
I don't necessarily want to only limit the web frontend to my workstation, but collaborate on the results...

**Comment by pcuzner** [comment]
it doesn't have to be on your workstation. I run it on vm in the vmware lab for example - which makes it accessible for collaboration? Would prefer to use it as it is to sort out the workflows, and then look at how we package and deploy later..thoughts?
@mulbc  ^^

**Comment by mulbc** [comment]
Why don't we package it up as a container and deploy it next to the other pods? Then use a svc & route to make it accessible...
No time pressure on my bugs... just noting them down

**Comment by pcuzner** [comment]
This is now done and available on master. closing issue
