### ISSUE TITLE
Use anti-affinity rules to spread out fio workers on different nodes

### ISSUE THREAD

**Issue by mulbc** [pcuzner/fioloadgen#8]
Using affinity rules we can tell Kubernetes to try to spread the fio workers on different nodes:
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity

**Comment by pcuzner** [comment]
@mulbc Agree - but we'll likely have more pods than nodes, so would using preferredDuringSchedulingIgnoredDuringExecution make sense?

**Comment by mulbc** [comment]
Yes please :)

**Comment by pcuzner** [comment]
implemented in 1.5
